# Generated by Django 3.0 on 2024-03-31 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_triage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('bug_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
