# Generated by Django 3.0 on 2024-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_triage_app', '0002_bugfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugfeature',
            name='severity',
        ),
    ]
