# Generated by Django 3.0 on 2024-04-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_triage_app', '0003_remove_bugfeature_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugfeature',
            name='bug_reporter',
        ),
    ]
